# Generated by Django 4.2.6 on 2023-11-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_service_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_Service',
            new_name='CustomerService_Stock',
        ),
    ]
