# Generated by Django 4.2.6 on 2023-12-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer_service_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service_note',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
