# Generated by Django 4.2.6 on 2023-11-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_service_value_alter_stock_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice_stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
